language: node_js
node_js:
  - "14"

script:
  - npm run ci

install:
  - npm cache clean --force
  - npm install

deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/public
  domain: passbox.surge.sh
